POST {{Api_HostAddress}}/api/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "privateEmail": "student.personal@example.com",
  "code": "123456",
  "newPassword": "NewPa55word!"
}
