FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime

WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8080 \
    ASPNETCORE_ENVIRONMENT=Production

COPY api/ ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "Api.dll"]
